version: "3.9"

services:
  postgres:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Pedrogmr1"
      POSTGRES_DB: "FortSeg"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      app_network:

  app:
    build: ./gps
    container_name: "app"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      app_network:

networks:
  app_network:

volumes:
  postgres-data:

